#ifndef MGCORE_ERRNO_H
#define MGCORE_ERRNO_H

#define MGCORE_EPERM 1
#define MGCORE_ENOENT 2
#define MGCORE_ESRCH 3
#define MGCORE_EINTR 4
#define MGCORE_EIO 5
#define MGCORE_ENXIO 6
#define MGCORE_E2BIG 7
#define MGCORE_ENOEXEC 8
#define MGCORE_EBADF 9
#define MGCORE_ECHILD 10
#define MGCORE_EAGAIN 11
#define MGCORE_ENOMEM 12
#define MGCORE_EACCES 13
#define MGCORE_EFAULT 14
#define MGCORE_EBUSY 16
#define MGCORE_EEXIST 17
#define MGCORE_ENODEV 19
#define MGCORE_ENOTDIR 20
#define MGCORE_EISDIR 21
#define MGCORE_EINVAL 22
#define MGCORE_ENFILE 23
#define MGCORE_EMFILE 24
#define MGCORE_ENOTTY 25
#define MGCORE_EFBIG 27
#define MGCORE_ENOSPC 28
#define MGCORE_ESPIPE 29
#define MGCORE_EROFS 30
#define MGCORE_ENOSYS 38
#define MGCORE_ENOTEMPTY 39
#define MGCORE_ENAMETOOLONG 36

#endif
